export const styles = {
  container: {
    minHeight: '100vh',
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#0f172a',
  },
  backgroundGradient: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background:
      'linear-gradient(135deg, #0f172a 0%, #1a1f3a 25%, #2d1b4e 50%, #1a1f3a 75%, #0f172a 100%)',
    backgroundSize: '400% 400%',
    animation: 'gradientShift 15s ease infinite',
    zIndex: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    padding: '40px 20px',
    maxWidth: '900px',
    margin: '0 auto',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  step: {
    animation: 'slideUp 0.5s ease',
  },
  header: {
    textAlign: 'center',
    marginBottom: '40px',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '20px',
  },
  logoIcon: {
    fontSize: '48px',
    marginRight: '16px',
  },
  title: {
    fontSize: '42px',
    fontWeight: '700',
    color: '#ffffff',
    margin: '0 0 12px 0',
    letterSpacing: '-0.5px',
  },
  subtitle: {
    fontSize: '16px',
    color: '#cbd5e1',
    margin: '0',
    fontWeight: '400',
  },
  card: {
    background: 'rgba(15, 23, 42, 0.8)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(148, 163, 184, 0.2)',
    borderRadius: '16px',
    padding: '40px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    background: 'transparent',
    border: 'none',
    color: '#cbd5e1',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    marginBottom: '24px',
    transition: 'color 0.2s',
    padding: '8px 0',
  },
  tabContainer: {
    display: 'flex',
    gap: '12px',
    marginBottom: '32px',
    borderBottom: '1px solid rgba(148, 163, 184, 0.2)',
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 24px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s',
    color: '#94a3b8',
    borderBottom: '2px solid transparent',
  },
  tabActive: {
    color: '#6366f1',
    borderBottomColor: '#6366f1',
  },
  tabInactive: {
    color: '#64748b',
  },
  uploadSection: {
    marginBottom: '32px',
  },
  dropZone: {
    border: '2px dashed rgba(99, 102, 241, 0.5)',
    borderRadius: '12px',
    padding: '48px 24px',
    textAlign: 'center',
    transition: 'all 0.2s',
    backgroundColor: 'rgba(99, 102, 241, 0.05)',
    marginBottom: '20px',
  },
  dropZoneLabel: {
    cursor: 'pointer',
    display: 'block',
  },
  dropZoneText: {
    fontSize: '16px',
    color: '#e2e8f0',
    margin: '12px 0 4px 0',
    fontWeight: '600',
  },
  dropZoneSubtext: {
    fontSize: '14px',
    color: '#94a3b8',
    margin: '0',
  },
  highlight: {
    color: '#6366f1',
    fontWeight: '700',
  },
  hiddenInput: {
    display: 'none',
  },
  fileSelected: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    border: '1px solid rgba(16, 185, 129, 0.3)',
    borderRadius: '8px',
    color: '#10b981',
    fontSize: '14px',
    fontWeight: '500',
  },
  manualInputSection: {
    marginBottom: '32px',
  },
  textarea: {
    width: '100%',
    minHeight: '200px',
    padding: '16px',
    backgroundColor: 'rgba(51, 65, 85, 0.5)',
    border: '1px solid rgba(148, 163, 184, 0.2)',
    borderRadius: '8px',
    color: '#e2e8f0',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'vertical',
    outline: 'none',
    transition: 'all 0.2s',
  },
  primaryButton: {
    width: '100%',
    padding: '14px 24px',
    backgroundColor: '#6366f1',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDisabled: {
    backgroundColor: '#6366f1',
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  secondaryButton: {
    padding: '12px 24px',
    backgroundColor: 'transparent',
    border: '1px solid rgba(148, 163, 184, 0.3)',
    color: '#cbd5e1',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  profileSection: {
    display: 'flex',
    gap: '24px',
    alignItems: 'flex-start',
    marginBottom: '32px',
  },
  profileAvatar: {
    width: '80px',
    height: '80px',
    borderRadius: '12px',
    backgroundColor: '#6366f1',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    fontWeight: '700',
    flexShrink: 0,
  },
  profileName: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#ffffff',
    margin: '0 0 8px 0',
  },
  profileEmail: {
    fontSize: '14px',
    color: '#94a3b8',
    margin: '0 0 4px 0',
  },
  profilePhone: {
    fontSize: '14px',
    color: '#94a3b8',
    margin: '0',
  },
  divider: {
    height: '1px',
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
    margin: '24px 0',
  },
  summarySection: {
    marginBottom: '32px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#e2e8f0',
    margin: '0 0 12px 0',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  summaryText: {
    fontSize: '15px',
    color: '#cbd5e1',
    lineHeight: '1.6',
    margin: '0',
  },
  skillsSection: {
    marginBottom: '32px',
  },
  skillGroup: {
    marginBottom: '20px',
  },
  skillGroupTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#94a3b8',
    margin: '0 0 10px 0',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  skillsList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
  },
  skillTag: {
    padding: '6px 12px',
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    color: '#c7d2fe',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '500',
    border: '1px solid rgba(99, 102, 241, 0.3)',
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '20px',
    marginBottom: '20px',
  },
  optionCard: {
    background: 'rgba(15, 23, 42, 0.8)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(148, 163, 184, 0.2)',
    borderRadius: '12px',
    padding: '32px 24px',
    cursor: 'pointer',
    transition: 'all 0.3s',
    display: 'flex',
    flexDirection: 'column',
  },
  optionIcon: {
    fontSize: '48px',
    marginBottom: '16px',
  },
  optionTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#ffffff',
    margin: '0 0 12px 0',
  },
  optionDescription: {
    fontSize: '14px',
    color: '#cbd5e1',
    margin: '0 0 auto 0',
    lineHeight: '1.5',
  },
  optionFooter: {
    marginTop: '20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#94a3b8',
    fontSize: '13px',
    paddingTop: '16px',
    borderTop: '1px solid rgba(148, 163, 184, 0.2)',
  },
  optionLabel: {
    fontWeight: '500',
  },
  loadingOverlay: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '20px',
    zIndex: 100,
  },
  spinner: {
    width: '48px',
    height: '48px',
    border: '3px solid rgba(99, 102, 241, 0.3)',
    borderTop: '3px solid #6366f1',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  skillItem: {
    padding: '16px',
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    borderLeft: '3px solid #6366f1',
    borderRadius: '4px',
    marginBottom: '12px',
  },
  skillItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  skillItemName: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#e2e8f0',
    margin: '0',
  },
  badge: {
    padding: '4px 10px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#ffffff',
  },
  skillItemReason: {
    fontSize: '14px',
    color: '#cbd5e1',
    margin: '0',
  },
  phaseBlock: {
    marginBottom: '24px',
    padding: '16px',
    backgroundColor: 'rgba(51, 65, 85, 0.5)',
    borderRadius: '8px',
  },
  phaseTitle: {
    fontSize: '15px',
    fontWeight: '700',
    color: '#fbbf24',
    margin: '0 0 12px 0',
  },
  taskList: {
    listStyle: 'none',
    padding: '0',
    margin: '0',
  },
  taskItem: {
    fontSize: '14px',
    color: '#cbd5e1',
    margin: '8px 0',
    paddingLeft: '20px',
    position: 'relative',
  },
  careerSection: {
    marginBottom: '0',
  },
  careerLabel: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#94a3b8',
    margin: '0 0 8px 0',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  careerValue: {
    fontSize: '16px',
    color: '#e2e8f0',
    margin: '0',
    fontWeight: '500',
  },
  recommendationsTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#e2e8f0',
    margin: '0 0 16px 0',
  },
  recommendationCard: {
    padding: '16px',
    backgroundColor: 'rgba(34, 197, 94, 0.1)',
    borderLeft: '3px solid #22c55e',
    borderRadius: '4px',
    marginBottom: '12px',
  },
  recHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '8px',
  },
  recTitle: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#e2e8f0',
    margin: '0',
  },
  recSalary: {
    fontSize: '14px',
    color: '#22c55e',
    fontWeight: '600',
  },
  recTimeline: {
    fontSize: '13px',
    color: '#cbd5e1',
    margin: '8px 0',
    fontWeight: '400',
  },
  recRequirements: {
    fontSize: '13px',
    color: '#cbd5e1',
    margin: '4px 0 0 0',
    fontWeight: '400',
  },
  actionButtons: {
    display: 'flex',
    gap: '12px',
    marginTop: '32px',
    paddingTop: '24px',
    borderTop: '1px solid rgba(148, 163, 184, 0.2)',
  },
};
