export const styles = {
  container: {
    minHeight: '100vh',
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#f8fafc',
  },
  backgroundGradient: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)',
    backgroundSize: '400% 400%',
    animation: 'gradientShift 15s ease infinite',
    zIndex: 0,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    padding: '60px 20px',
    maxWidth: '900px',
    margin: '0 auto',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  step: {
    animation: 'slideUp 0.5s ease',
  },
  header: {
    textAlign: 'center',
    marginBottom: '48px',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '20px',
  },
  logoIcon: {
    fontSize: '48px',
    marginRight: '16px',
  },
  title: {
    fontSize: '42px',
    fontWeight: '700',
    color: '#1f2937',
    margin: '0 0 12px 0',
    letterSpacing: '-0.5px',
  },
  subtitle: {
    fontSize: '16px',
    color: '#6b7280',
    margin: '0',
    fontWeight: '400',
  },
  card: {
    background: '#ffffff',
    backdropFilter: 'blur(10px)',
    border: '1px solid #e5e7eb',
    borderRadius: '24px',
    padding: '48px',
    boxShadow: '0 10px 30px -5px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.04)',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    background: 'transparent',
    border: 'none',
    color: '#6b7280',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    marginBottom: '24px',
    transition: 'color 0.2s',
    padding: '8px 0',
  },
  tabContainer: {
    display: 'flex',
    gap: '12px',
    marginBottom: '40px',
    borderBottom: '1px solid #e5e7eb',
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 24px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s',
    color: '#9ca3af',
    borderBottom: '2px solid transparent',
  },
  tabActive: {
    color: '#6366f1',
    borderBottomColor: '#6366f1',
  },
  tabInactive: {
    color: '#d1d5db',
  },
  uploadSection: {
    marginBottom: '40px',
  },
  dropZone: {
    border: '2px dashed rgba(99, 102, 241, 0.5)',
    borderRadius: '12px',
    padding: '56px 24px',
    textAlign: 'center',
    transition: 'all 0.2s',
    backgroundColor: '#f0f4ff',
    marginBottom: '20px',
  },
  dropZoneLabel: {
    cursor: 'pointer',
    display: 'block',
  },
  dropZoneText: {
    fontSize: '16px',
    color: '#1f2937',
    margin: '12px 0 4px 0',
    fontWeight: '600',
  },
  dropZoneSubtext: {
    fontSize: '14px',
    color: '#6b7280',
    margin: '0',
  },
  highlight: {
    color: '#6366f1',
    fontWeight: '700',
  },
  hiddenInput: {
    display: 'none',
  },
  fileSelected: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    backgroundColor: '#d1fae5',
    border: '1px solid #6ee7b7',
    borderRadius: '8px',
    color: '#047857',
    fontSize: '14px',
    fontWeight: '500',
  },
  manualInputSection: {
    marginBottom: '40px',
  },
  textarea: {
    width: '100%',
    minHeight: '220px',
    padding: '16px',
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    color: '#1f2937',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'vertical',
    outline: 'none',
    transition: 'all 0.2s',
  },
  primaryButton: {
    width: '100%',
    padding: '14px 24px',
    backgroundColor: '#6366f1',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDisabled: {
    backgroundColor: '#6366f1',
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  secondaryButton: {
    padding: '12px 24px',
    backgroundColor: 'transparent',
    border: '1px solid #e5e7eb',
    color: '#6b7280',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  profileSection: {
    display: 'flex',
    gap: '24px',
    alignItems: 'flex-start',
    marginBottom: '40px',
  },
  profileAvatar: {
    width: '80px',
    height: '80px',
    borderRadius: '12px',
    backgroundColor: '#6366f1',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    fontWeight: '700',
    flexShrink: 0,
  },
  profileName: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#1f2937',
    margin: '0 0 8px 0',
  },
  profileEmail: {
    fontSize: '14px',
    color: '#6b7280',
    margin: '0 0 4px 0',
  },
  profilePhone: {
    fontSize: '14px',
    color: '#6b7280',
    margin: '0',
  },
  divider: {
    height: '1px',
    backgroundColor: '#e5e7eb',
    margin: '32px 0',
  },
  summarySection: {
    marginBottom: '40px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#1f2937',
    margin: '0 0 16px 0',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  summaryText: {
    fontSize: '15px',
    color: '#4b5563',
    lineHeight: '1.6',
    margin: '0',
  },
  skillsSection: {
    marginBottom: '40px',
  },
  skillGroup: {
    marginBottom: '24px',
  },
  skillGroupTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#6b7280',
    margin: '0 0 12px 0',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  skillsList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
  },
  skillTag: {
    padding: '6px 12px',
    backgroundColor: '#f0f4ff',
    color: '#4f46e5',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '500',
    border: '1px solid #ddd6fe',
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '28px',
    marginBottom: '28px',
  },
  optionCard: {
    background: '#f9fafb',
    backdropFilter: 'blur(10px)',
    border: '1px solid #e5e7eb',
    borderRadius: '12px',
    padding: '36px 24px',
    cursor: 'pointer',
    transition: 'all 0.3s',
    display: 'flex',
    flexDirection: 'column',
  },
  optionIcon: {
    fontSize: '48px',
    marginBottom: '20px',
  },
  optionTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#1f2937',
    margin: '0 0 16px 0',
  },
  optionDescription: {
    fontSize: '14px',
    color: '#6b7280',
    margin: '0 0 auto 0',
    lineHeight: '1.5',
  },
  optionFooter: {
    marginTop: '20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#9ca3af',
    fontSize: '13px',
    paddingTop: '20px',
    borderTop: '1px solid #e5e7eb',
  },
  optionLabel: {
    fontWeight: '500',
  },
  loadingOverlay: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '20px',
    zIndex: 100,
  },
  spinner: {
    width: '48px',
    height: '48px',
    border: '3px solid #e5e7eb',
    borderTop: '3px solid #6366f1',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  skillItem: {
    padding: '16px',
    backgroundColor: '#f0f4ff',
    borderLeft: '3px solid #6366f1',
    borderRadius: '4px',
    marginBottom: '16px',
  },
  skillItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  skillItemName: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#1f2937',
    margin: '0',
  },
  badge: {
    padding: '4px 10px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#ffffff',
  },
  skillItemReason: {
    fontSize: '14px',
    color: '#6b7280',
    margin: '0',
  },
  phaseBlock: {
    marginBottom: '32px',
    padding: '16px',
    backgroundColor: '#fef3c7',
    borderRadius: '8px',
  },
  phaseTitle: {
    fontSize: '15px',
    fontWeight: '700',
    color: '#b45309',
    margin: '0 0 16px 0',
  },
  taskList: {
    listStyle: 'none',
    padding: '0',
    margin: '0',
  },
  taskItem: {
    fontSize: '14px',
    color: '#92400e',
    margin: '8px 0',
    paddingLeft: '20px',
    position: 'relative',
  },
  careerSection: {
    marginBottom: '0',
  },
  careerLabel: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#6b7280',
    margin: '0 0 8px 0',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  careerValue: {
    fontSize: '16px',
    color: '#1f2937',
    margin: '0',
    fontWeight: '500',
  },
  recommendationsTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#1f2937',
    margin: '0 0 24px 0',
  },
  recommendationCard: {
    padding: '16px',
    backgroundColor: '#dcfce7',
    borderLeft: '3px solid #22c55e',
    borderRadius: '4px',
    marginBottom: '16px',
  },
  recHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '8px',
  },
  recTitle: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#1f2937',
    margin: '0',
  },
  recSalary: {
    fontSize: '14px',
    color: '#22c55e',
    fontWeight: '600',
  },
  recTimeline: {
    fontSize: '13px',
    color: '#6b7280',
    margin: '8px 0',
    fontWeight: '400',
  },
  recRequirements: {
    fontSize: '13px',
    color: '#6b7280',
    margin: '4px 0 0 0',
    fontWeight: '400',
  },
  actionButtons: {
    display: 'flex',
    gap: '12px',
    marginTop: '40px',
    paddingTop: '32px',
    borderTop: '1px solid #e5e7eb',
  },
};
